services:
    sonata.admin.store:
        class: DataBundle\Admin\StoreAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "ORM", label: "Store" }
        arguments:
            - ~
            - DataBundle\Entity\Store
            - ~
        calls:
            - [ setTranslationDomain, [StoreBundle]]
    sonata.admin.transaction:
        class: DataBundle\Admin\TransactionAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "MongoDB", label: "Transaction" }
        arguments:
            - ~
            - DataBundle\Document\Transaction
            - ~
                    