imports:
    - { resource: "@UserBundle/Resources/config/admin.yml" }
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin] 
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes

sonata_admin:
    security:
        handler:              sonata.admin.security.handler.noop
        information:

            # Prototype
            id:                   []
        admin_permissions:

            # Defaults:
            - CREATE
            - LIST
            - DELETE
            - UNDELETE
            - EXPORT
            - OPERATOR
            - MASTER
        object_permissions:

            # Defaults:
            - VIEW
            - EDIT
            - DELETE
            - UNDELETE
            - OPERATOR
            - MASTER
            - OWNER
        acl_user_manager:     ~         # Name of the user manager service used to retrieve ACL users
    title:                Sonata Admin
    title_logo:           bundles/sonataadmin/logo_title.png
    options:
        html5_validate:                         true      # use html5 validation
        confirm_exit:                           true      # enabled confirmation when quitting with unsaved changes
        use_select2:                            true      # enable select2
        use_icheck:                             true      # enable iCheck
        pager_links:                            10         # pager max links to display
        dropdown_number_groups_per_colums:      2         # max items per column in dropdown menu (add button in top nav)
        title_mode:           'both'                      # 'both', 'single_text' or 'single_image'
    dashboard:
        groups:

            # Prototype
            id:
                label:                ~
                label_catalogue:      ~
                items:                []
                item_adds:            []
                roles:                []
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
    admin_services:

        # Prototype
        id:
            model_manager:        ~
            form_contractor:      ~
            show_builder:         ~
            list_builder:         ~
            datagrid_builder:     ~
            translator:           ~
            configuration_pool:   ~
            #router:               ~
            validator:            ~
            security_handler:     ~
            label:                ~
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig 
    extensions:

        # Prototype
        id:
            admins:               []
            excludes:             []
            implements:           []
            extends:              []
            instanceof:           []
    persist_filters:      false     # set to true to persist filter settings per admin module in the user's session  