imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: fos_elastica.yml }
#    - { resource: "@UserBundle/Resources/config/admin.yml" }
    - { resource: "@DataBundle/Resources/config/admin.yml" }
    - { resource: "@SonataAdminBundle/Resources/config/services.yml" }
    - { resource: "@MapsBundle/Resources/config/services.yml" }
#    - { resource: "@ApplicationSonataUserBundle/Resources/config/services.yml" }
                            
doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
    default_database: test_database
    document_managers:
        default:
            mappings:
                ApplicationSonataUserBundle: ~
                SonataUserBundle: ~
                FOSUserBundle: ~
            auto_mapping: true        
sonata_user:
    security_acl: true
    manager_type: mongodb # can be orm or mongodb            
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin] 
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes
        sonata.admin.block.search_result:
            contexts: [admin]
parameters:
    locale: en
    sonata.user.form.type.security_roles.class: Sonata\UserBundle\Form\Type\SecurityRolesType

    sonata.user.profile.form.type.class:            Sonata\UserBundle\Form\Type\ProfileType
    sonata.user.profile.form.handler.default.class: Sonata\UserBundle\Form\Handler\ProfileFormHandler

    sonata.user.admin.user.class:              Application\Sonata\UserBundle\Admin\UserAdmin
    sonata.user.admin.user.entity:             Application\Sonata\UserBundle\Document\User
    sonata.user.admin.user.controller:         SonataAdminBundle:CRUD
#    sonata.user.admin.user.translation_domain: SonataUserBundle

    sonata.user.admin.group.class:              Sonata\UserBundle\Admin\Entity\GroupAdmin
    sonata.user.admin.group.controller:         SonataAdminBundle:CRUD
#    sonata.user.admin.group.translation_domain: %sonata.user.admin.user.translation_domain%

    sonata.user.admin.groupname: sonata_user            
sonata_admin:
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig              

fos_user:
    db_driver:      mongodb # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Document\User


    group:
        group_class:   Application\Sonata\UserBundle\Document\Group
        group_manager: sonata.user.mongodb.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

    service:
        user_manager: sonata.user.mongodb.user_manager            
# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
#parameters:
#    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: gmail
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:                 false
    encryption:           ~
    auth_mode:            ~
    spool:
        type:                 file
        path:                 '%kernel.cache_dir%/swiftmailer/spool'
    sender_address:       ~
    antiflood:
        threshold:            99
        sleep:                0
    delivery_addresses:   []
    disable_delivery:     ~
    logging:              '%kernel.debug%'
