# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
          id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:      ^/
            anonymous:    true
            provider:     fos_userbundle
            form_login:
                provider: fos_userbundle
                login_path: login
                use_forward: false
                check_path: login_check
                failure_path: null
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path:            /
            logout:
                path: /logout
                target: /
                invalidate_session: false
    encoders :
        UserBundle\Entity\User: plaintext
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: IS_AUTHENTICATED_ANONYMOUSLY }