# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    survey.repository.container_aware:
#        class: CoreBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#survey.repository.container_aware:
#    class: Demo\SurveyBundle\Repository\SurveyRepository
#    arguments: [@service_container]
