<?php

namespace DataBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Symfony\Component\DependencyInjection\Container;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends DocumentRepository
{
	private $container ;
	
	public function setContainer(Container $container) {
		$this->container = $container;
	}

	
	public function findTransaction($q){
		    $finder = $this->container->get('fos_elastica.finder.app.transaction');
		    $transactions = $finder->find($q);
            return $transactions;
		}
}
