<?php

namespace DataBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Symfony\Component\HttpFoundation\Request;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends DocumentRepository
{
	
	public function findTransaction(Request $request){
		    $finder = $this->container->get('fos_elastica.finder.app.transaction');
		    $transactions = $finder->find($request->get('q'));
            return $transactions;
		}
}
