<?php

namespace DataBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends DocumentRepository
{
}
