services:
    application_sonata_user.admin.user:
        class: Application\Sonata\UserBundle\Admin\UserAdmin
        arguments: [~, Application\Sonata\UserBundle\Document\User, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: admin, label: User }
